#!/usr/bin/env python

# This is the script to connect ABCluster with VASP.
#

import os
import sys

elements = [
    ("Au", 4)
]


xyz_fn = sys.argv[1]    # XYZ structure generated by ABCluster.
b1 = sys.argv[2]  # box x1
b2 = sys.argv[3]  # box y2
b3 = sys.argv[4]  # box z3

a1 = [float(b1), 0.0, 0.0]
a2 = [0.0, float(b2), 0.0]
a3 = [0.0, 0.0, float(b3)]

# Write POSCAR.
coords = []
with open(xyz_fn, "r") as fd:
    lines = fd.readlines()
    for line in lines[2:]:
        line = line.split()
        coords.append([line[0], float(line[1]),
                       float(line[2]), float(line[3])])
with open("POSCAR", "w") as fd:
    fd.write("Input xyz\n")
    fd.write("1.0\n")
    fd.write("%15.8f %15.8f %15.8f\n" % (a1[0], a1[1], a1[2]))
    fd.write("%15.8f %15.8f %15.8f\n" % (a2[0], a2[1], a2[2]))
    fd.write("%15.8f %15.8f %15.8f\n" % (a3[0], a3[1], a3[2]))
    line_ele = ' '.join([e[0] for e in elements])
    line_num = ' '.join([str(e[1]) for e in elements])
    fd.write(line_ele+"\n")
    fd.write(line_num+"\n")
    fd.write("Cartesian\n")
    for coord in coords:
        fd.write("%15.8f %15.8f %15.8f\n" % (coord[1], coord[2], coord[3]))

